---Q Who are the top ten most frequent users of DOTS services? 

SELECT TOP(10) p.uId,u.firstName,u.lastName, (SUM(ISNULL(DATEDIFF(minute,[startTimeChrg],[endTimeChrg]),0)) + SUM(ISNULL(DATEDIFF(minute,[startTimePrkng],[endTimePrkng]),0))) AS 'ParkingDuration'
FROM [GreenTerps.GeneratesReport] g, [GreenTerps.PaymentGateway] p, [GreenTerps.User] u
WHERE g.pId = p.pId and p.uId=u.uId
GROUP BY p.uId,u.firstName,u.lastName
ORDER BY ParkingDuration desc;

--- Q What is the revenue generated by DOTS for all the dates
SELECT g.Date, SUM(st.chargingRatePerHour* DATEDIFF(MINUTE,g.[startTimeChrg],g.[endTimeChrg])/60) AS 'charging Revenue', SUM(st.[parkingRatePerHour]* DATEDIFF(MINUTE,g.[startTimePrkng],g.[endTimePrkng])/60) AS 'parking revenue'
FROM [GreenTerps.GeneratesReport] g, [GreenTerps.Sensor] s, [GreenTerps.Station] st
WHERE g.sensorId=s.sensorId AND s.stnId=st.stnId 
GROUP BY g.Date


--- Q Which is the most preferred method of payment by users? 
SELECT DISTINCT TYPE, count(uid) FROM [GreenTerps.PaymentGateway]  
GROUP BY TYPE

---Q What are  the details  of users whose subscription is ending on 2019-12-31?
SELECT * FROM [GreenTerps.User] WHERE uId IN (SELECT uId FROM [GreenTerps.Subscribes] WHERE endDate='2019-12-31')

---Q What is the percentage of users who have a permit to park inside the Campus? 
select hasPermit, count(*) * 100 / (select count(*) from [GreenTerps.User] ) as 'Percentage of users with/without Permit'
From [GreenTerps.User] group by hasPermit

---Q. What is the duration for which a user has parked at the station and its details?
SELECT p.uId,g.startTimePrkng,g.endTimePrkng, ISNULL(DATEDIFF(minute,startTimePrkng,endTimePrkng),0) AS 'Parking Duration(mins)'
FROM [GreenTerps.GeneratesReport] g, [GreenTerps.PaymentGateway] p
WHERE g.pId=p.pId 
GROUP BY p.uId,g.startTimePrkng,g.endTimePrkng;

---Q. Which user had parked for the longest duration?
SELECT TOP(1) p.uId,u.firstName,u.lastName,g.pId, MAX(ISNULL(DATEDIFF(minute,startTimePrkng,endTimePrkng),0)) AS 'ParkingDuration'
FROM [GreenTerps.GeneratesReport] g,[GreenTerps.PaymentGateway] p, [GreenTerps.User] u
WHERE g.pId = p.pId and p.uId=u.uId
GROUP BY g.pId,p.uId,u.firstName,u.lastName
ORDER BY ParkingDuration desc;











